version: "3.9"

# networks:
#   web:
#     external: true
#   internal:
#     external: false

services:
  site_dev:
    image: site:latest
    container_name: site_dev
    build:
      context: ./
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules #empty mount to not overwrite node_modules
    environment:
      - NODE_ENV="development"
  
  site_prod:
    image: nginx
    volumes:
      - $PWD/dist:/usr/share/nginx/html
    container_name: site_prod
    restart: unless-stopped
    network_mode: traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`agentzhao.me`)"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.port=80"


